version: '3.3'
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/tmp/nginx.conf
    environment:
      - FLASK_SERVER_ADDR=web:9091
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
        - 80:80
    depends_on:
        - web
    networks:
      - frontend

  web:
    container_name: container_web
    build: ./app
    restart: always
    links:
      - db
    environment:
      - FLASK_SERVER_PORT=9091
    networks:
      - backend
      - frontend
  db:
    image: mongo:latest
    hostname: test_mongodb
    environment:
      - MONGO_INITDB_DATABASE=quizdb
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ./data-volume:/data/db
    ports:
      - 27017:27017
    networks:
      - backend

  tests:
    build: ./app
    depends_on:
      - db
      - web
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
      - .:/app
    command: ["pytest","app/tests/test.py"]
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge