version: '3.3'
services:
    web:
        build: ./app
        ports:
            - "5000:5000"
        volumes:
            - ./app:/app
        restart: always
        links:
            - db

    db:
        image: mysql:5.7
        ports:
          - "32000:3306"
        environment:
          MYSQL_ROOT_PASSWORD: 'root'
